version: '3.8'

networks:
  dockernet:
    name: inception

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    networks:
      - dockernet
    depends_on:
      - wordpress
    volumes:
      - wp-data:/var/www/html
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    expose:
      - "9000"
    networks:
      - dockernet
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      DB_HOST: ${DB_HOST}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wp-data:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    networks:
      - dockernet
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  wp-data:
    driver: local
    driver_opts:
      type: none
      device: /home/kglebows/data/wp-data
      o: bind
  db-data:
    driver: local
    driver_opts:
      type: none
      device: /home/kglebows/data/db-data
      o: bind